<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5qIx4TY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5qIx4TY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5qIx4TY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5qIx4TY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5qIx4TY\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5qIx4TY',
    'container.build_id' => '0681357b',
    'container.build_time' => 1522425595,
));
